import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:logger/logger.dart';
import '../app/data/file_manager/file_manager.dart';
import '../core/logs/logger_instance.dart';

int mockDataCount = 499;


List<String> mockNames = ["Dereck Olomi"];
List<String> mockCountries = [];
class MockText{
  MockText._();
  static const String longText = 'Long text is very long. I like long text because its very long. The longer the better. This looks like it was generated by a bot';
}
Logger logger = AppLogger.instance.logger;






void saveDataToFile(){
  FileManager fileManager = FileManager();
  Map<String,dynamic> data = {'names': mockNames,'countries':mockCountries};
  fileManager.writeJsonFile(data);
}
Future<void> loadMockNamesAndCountries()async{
  FileManager fileManager = FileManager();
  await fileManager.readJsonFile().then((value) {
    for(dynamic element in value['names']){
     mockNames.add(element.toString());
    }
    for(dynamic element in value['countries']){
      mockCountries.add(element.toString());
    }
  });
}


Future<void>fetchMockNamesAndCountries()async{
  for(int index=0;index < mockDataCount;index++){
    await http.get(Uri.parse('http://api.namefake.com/')).then((value) {
      if(value.statusCode == 200){
        mockNames.add(jsonDecode(value.body)['name']);
        mockCountries.add(jsonDecode(value.body)['address']);
        index++;
        logger.i('Fetching data point $index');
      }
    });
  }
  saveDataToFile();

}


